### ISSUE TITLE
Advances in Ecosystem Modelling crashes game during project complete dialogue

### ISSUE THREAD

**Issue by entityleak** [frnsys/half_earth#150]
Something to do with dialogue tree maybe?

When clicking 'Like what?' dialogue option

```
runtime-core.esm-bundler.js:6620 [Vue warn]: Unhandled error during execution of native event handler 
  at <Dialogue key=0 dialogue= {lines: {…}, root: 0} effects= []  ... > 
  at <Update key=0 update= {id: 110, type: 'Project'} onDone=fn<bound dismissUpdate> > 
  at <Events key=1 > 
  at <App>
```
```
warn @ runtime-core.esm-bundler.js:6620
logError @ runtime-core.esm-bundler.js:6794
handleError @ runtime-core.esm-bundler.js:6786
callWithErrorHandling @ runtime-core.esm-bundler.js:6740
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
invoker @ runtime-dom.esm-bundler.js:357
half_earth_engine_bg.js:740 Uncaught Error: recursive use of an object detected which would lead to unsafe aliasing in rust
    at __wbindgen_throw (half_earth_engine_bg.js:740:1)
    at 917c587a3af119a75fba.module.wasm:0x8784a
    at 917c587a3af119a75fba.module.wasm:0x87866
    at 917c587a3af119a75fba.module.wasm:0x8693e
    at 917c587a3af119a75fba.module.wasm:0x84bea
    at GameInterface.apply_branch_effects (half_earth_engine_bg.js:477:9)
    at Object.applyBranchEffects (game.js:170:1)
    at Proxy.selectChoice (Dialogue.vue:182:7)
    at onClick (Dialogue.vue:27:55)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737:1)
```

**Comment by frnsys** [comment]
yikes that doesn't look good, I'll take a look

**Comment by frnsys** [comment]
Some notes for myself:

Problem seems to be because project outcomes now have dialogue--they used to just have one bit of text that would show up, but with dialogue that means there may be branching involved.

When a branch is rendered, we run `applyBranchEffects` (in `Dialogue.vue`) which takes an event id and a branch id. So it assumes that this dialogue has an associated event.

Then in the rust code this calls `apply_branch_effects`, which looks up an event by event id and then a branch id. The rust exception is an indexing panic.

The data being passed is: `eventId: undefined, branchId: branchId: 5adc3f61-3079-4cee-a807-69b0c3c84c1a`, which makes sense because there isn't actually an event being passed, and that `branchId` is the one internal to the dialogue, not meant for rust.

So I could either re-write things so that we have branch effects working properly for projects in addition to events, or I can just make it so that project dialogue can't have any branch effects. The latter's way easier and it doesn't look like we're using branch effects in project outcome dialogues anyways.
