### ISSUE TITLE
"Orbital Space Settlements" Project cost unrealistically low

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#291]
![image](https://github.com/user-attachments/assets/0ed224c6-37f2-44f8-ae68-5f75f8c0f8e0)
I think something with the calculation of build time reduction on the space projects is wrong, as both the Outer Space Settlements and the Orbital Space Settlements seem to be completed way too fast compared to their stated cost. Maybe has something to do with Accelerationist's bonus being applied too much?

**Comment by frnsys** [comment]
Turns out this is actually the same bug as #288 -- if you're researching Biosphere 3 its effects would get applied every year instead of just when it's completed, which is why you would get 50 research points (10 for each year over a planning cycle) and its discount on space projects would also compound, so this is actually also closed by c3b331c8ddfd2d78be8ecb09569534720dce7394
